tap 'homebrew/bundle'
tap 'homebrew/services'

brew 'adr-tools'
brew 'asdf'
brew 'awscli'
# brew 'csvkit'
brew 'direnv'
# brew 'docker'
# brew 'docker-compose'
# brew 'forego'
# brew 'go'
# brew 'heroku/brew/heroku'
brew 'hub'
# brew 'iamy'
brew 'jq'
brew 'khell/homebrew-srm/srm', args: ['build-from-source']
# brew 'libxml2'
brew 'libyaml'
# brew 'mas'
# brew 'postgresql'
# brew 'puma/puma/puma-dev'
# brew 'pyenv'
# brew 'rbenv'
# brew 'rbenv-default-gems'
# brew 'redis'
# brew 'sj26/git-buildkite/git-buildkite'
brew 'wget'
# brew 'zsh'

# cask 'authy'
cask 'aws-vault'
# cask 'db-browser-for-sqlite'
# cask 'diffmerge'
# cask 'gimp'
# cask 'google-chrome'
# cask 'gpg-suite'
# cask 'insomnia'
# cask 'iterm2'
# cask 'java'
# cask 'keybase'
# cask 'pgadmin4'
# cask 'sequel-pro'

# cask 'font-source-code-pro'

# Signing in to the Mac App Store is temp disabled (https://github.com/mas-cli/mas#-sign-in) as such it can't be used to download apps
# mas '1Password 7', id: 1333542190
# mas 'Slack', id: 803453959
